taskui/Pages/CreatePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics.Tracing;
using taskui.Models;
using taskui.Services;

namespace taskui.Pages
{
    public class CreatePageModel : PageModel
    {
        private readonly IDataAccess dataAccess_;
        public CreatePageModel(IDataAccess dataAccess)
        {
            dataAccess_ = dataAccess;
        }

        [BindProperty(SupportsGet = true)]
        public int IncrementCount { get; set; } = 0;

        public void OnGet()
        {
        }
        public IActionResult OnPostAddButton()
        {
            IncrementCount = IncrementCount + 1;
            //Console.WriteLine("\add detail button\n");

            return Redirect($"/create/{IncrementCount}");
        }
        public IActionResult OnPostRemoveButton() 
        {
            IncrementCount = IncrementCount - 1;
            //Console.WriteLine("\nremove detail button\n");

            return Redirect($"/create/{IncrementCount}");
        }

        public IActionResult Test()
        {
            return Redirect($"/create/{IncrementCount}");
        }
    }
}

taskui/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace taskui.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

taskui/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using taskui.Models;
using taskui.Services;

namespace taskui.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IDataAccess dataAccess_;

        public IndexModel(IDataAccess dataAccess)
        {

            dataAccess_ = dataAccess;
        }

        public List<Header> HeaderList { get; set; } = new List<Header>() { };
        public int FirstHeader { get; set; }
        [BindProperty(SupportsGet = true)]
        public int paginationId { get; set; } = 0;

        public async Task OnGet()
        {
            var tempHeader = await dataAccess_.GetHeaderList();
            var tempList = tempHeader.OrderBy(item => item.ReleaseDate).Reverse().ToList();

            paginationId = paginationId * 5;
            if (paginationId == 0)
            {
                //paginationId = 1;
            }

            HeaderList = tempList; 

            // testing pagination
            try
            {
                //var result = tempList.GetRange(5, 5);
                //await Console.Out.WriteLineAsync($"{result.Count()}");
            } catch (Exception ex) { await Console.Out.WriteLineAsync($"error TC {ex}"); }
            //await Console.Out.WriteLineAsync($"headerCount: {HeaderList.Count()}");

            if (HeaderList.Count != 0)
            {
                var firstItem = HeaderList.OrderBy(item => item.ReleaseDate).Reverse().First(); 
                FirstHeader = firstItem.HeaderId;
            }
        }
    }
}

taskui/Pages/TableView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using taskui.Models;
using taskui.Services;

namespace taskui.Pages
{
    public class TableViewModel : PageModel
    {
        private readonly IDataAccess dataAccess_;

        public TableViewModel(IDataAccess dataAccess)
        {

            dataAccess_ = dataAccess;
        }
        public List<Header> HeaderList { get; set; }

        [BindProperty]
        public int TextEditorCount { get; set; } = 0;
        public async Task OnGet()
        {
            var tempHeader = await dataAccess_.GetHeaderList();
            HeaderList = tempHeader.OrderBy(item => item.ReleaseDate).Reverse().ToList();

            //await Console.Out.WriteLineAsync($"\n editCount: {HeaderList.Count()}\n");
        }
    }
}

taskui/Pages/CreatePage.cshtml
@page "/Create/{IncrementCount?}/{QueryString?}"
@model taskui.Pages.CreatePageModel
@using Syncfusion.EJ2.RichTextEditor

@{
    ViewData["Title"] = "Create Page";
}
<div class="white-bg-container">
    <p class="page-title">
        Fill up form
    </p>
    <form method="post">
        <div class="form-group mt-3">
            <label for="exampleInputEmail1">Release Number</label>
            <input name="releaseNameForm" value="Release number..." id="ReleaseName" type="text" class="form-control" placeholder="Release Number">
        </div>
        <div class="form-group mt-3">
            <label for="exampleInputPassword1">Release Date</label>
            <input name="releaseDateForm" value="@DateTime.Now.ToString("yyyy-MM-dd")" id="ReleaseDate" type="date" class="form-control" placeholder="Release Date">
        </div>
        <div class="form-group mt-3">
            <label for="exampleInputPassword1">Description</label>
            <input name="releaseShortDescriptionForm" value="Short description..." id="ShortDescription" type="text" class="form-control" placeholder="Short Description">
        </div>
        <div class="form-floating mt-4">
            <textarea name="releaseLongDescriptionForm" textcontent="test value here change this" id="LongDescription" 
                class="form-control" placeholder="Description here" style="height: 100px">Long description...
            </textarea>
            <label for="floatingTextarea2">Long Description</label>
        </div>
        <button type="submit" class="btn btn-dark mt-3 detailAddButton" id="" asp-page-handler="AddButton">Add a detail</button>
        @if (Model.IncrementCount > 0)
        {
            <button type="submit" class="btn btn-danger mt-3 detailAddButton" id="" asp-page-handler="RemoveButton">Remove a detail</button>
        }

        @*
            @if (Model.IncrementCount != 0)
            {
                <a class="btn btn-danger mt-3" href="/Create/reduceDetailCount">Remove a detail</a>
            }
        *@
    </form>

    <script>
        let rteObj

        function created(){
            rteObj = this;
            rteObj.insertImageSettings.saveFormat = 'Base64';
        }

        const releaseNumberInput = document.querySelector("#ReleaseName")
        const releaseDateInput = document.querySelector("#ReleaseDate")
        const releaseShortDescriptionInput = document.querySelector("#ShortDescription")
        const releaseLongDescriptionInput = document.querySelector("#LongDescription")

        document.querySelectorAll(".detailAddButton").forEach(detailButton => {
            detailButton.addEventListener("click", () => {
                //
                const saveInfo = {
                    releaseNumber: releaseNumberInput.value,
                    releaseDate: releaseDateInput.value,
                    releaseShortDescription: releaseShortDescriptionInput.value,
                    releaseLongDescription: releaseLongDescriptionInput.value
                }

                localStorage.setItem('loadInfo', JSON.stringify(saveInfo));

            })
        })

        window.onload = function(){
            if (localStorage.getItem("loadInfo") === null){
                console.log('no item 1')
                releaseNumberInput.value = "";
                //releaseDateInput.value = getItem.releaseDate;
                releaseShortDescriptionInput.value = "";
                releaseLongDescriptionInput.value = "";

            } else {
                console.log('exsits')
                const getItem = JSON.parse(localStorage.getItem("loadInfo"));
                
                releaseNumberInput.value = getItem.releaseNumber;
                releaseDateInput.value = getItem.releaseDate;
                releaseShortDescriptionInput.value = getItem.releaseShortDescription;
                releaseLongDescriptionInput.value = getItem.releaseLongDescription;
            }
        }

        /*
        if (localStorage.getItem("loadInfo") === null){
            console.log("no item")

            const saveInfo = {
                releaseNumber: releaseNumber.value, 
                releaseDate: releaseDate.value, 
                releaseShortDescription: releaseShortDescription.value, 
                releaseLongDescription: releaseLongDescription.value
            }

            localStorage.setItem('loadInfo', JSON.stringify(saveInfo));

        } else {
            const getItem = JSON.parse(localStorage.getItem("loadInfo"));

            releaseNumber.value = getItem.releaseNumber;
            releaseDate.value = getItem.releaseDate;
            releaseShortDescription.value = getItem.releaseShortDescription;
            releaseLongDescription.value = getItem.releaseLongDescription;

            localStorage.removeItem("loadInfo")
        }*/
    </script>

    @for (int i = 0; i < Model.IncrementCount; i++)
    {
        string defaultString = $"default-{i}";
        <div class="mt-3 RTE-container">
            <div class="input-group mb-3">
                <span class="input-group-text">@(i + 1)</span>
                <select class="form-select selectedTypeSelect" aria-label="Default select example">
                    <option selected value="1">Enhancement</option>
                    <option value="2">Bug Fix</option>
                </select>
                <input value="Detail title here..." type="text" class="form-control detailNameInput" placeholder="Detail Title" aria-label="Username">
            </div>
            <ejs-richtexteditor created="created" id="@defaultString" value="Detail Description here...">
            </ejs-richtexteditor>
        </div>
    }
    @if (Model.IncrementCount > 0)
    {
       <button id="submitBtn" data-btnType="createBtnSubmit" class="btn btn-primary mt-3">Submit</button>
    }
</div>

<ejs-scripts></ejs-scripts>

taskui/Pages/Index.cshtml
@page "/"
@using taskui.Models;
@model IndexModel
@using Syncfusion.EJ2.RichTextEditor
@{
    ViewData["Title"] = "Home page";
}
<div class="white-bg-container">
    @*
        <a href="https://stackoverflow.com/questions/49854127/how-add-header-and-footer-on-all-pdf-page-in-jspdf-with-addhtml-method">
            header footer pdf
        </a>
        <a href="https://www.w3docs.com/snippets/javascript/how-to-convert-the-image-into-a-base64-string-using-javascript.html">
            convert to base64    
        </a>
    *@

    <p class="page-title">
        View Release
    </p>
    <div class="accordion mt-5 " id="accordionExample">

        @foreach (var result in Model.HeaderList)
        {
            string accordionClassName = "";
            string buttonClassName = "";
            if (Model.FirstHeader == result.HeaderId)
            {
                accordionClassName = "accordion-collapse collapse show";
                buttonClassName = "accordion-button display-header";
            }
            else
            {
                accordionClassName = "accordion-collapse collapse";
                buttonClassName = "accordion-button collapsed display-header";
            }

            @if (result.Detail.Count() != 0) //result.Detail.Count() != 0)
            {
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="@buttonClassName" type="button" data-bs-toggle="collapse" data-bs-target="#@result.HeaderId" aria-expanded="false" aria-controls="@result.HeaderId">
                            <b>@result.ReleaseName.ToUpper()</b>&nbsp;- @result.ReleaseDate.ToString("yyyy-MM-dd")
                        </button>
                    </h2>
                    <div id="@result.HeaderId" class="@accordionClassName" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <div class="print-@result.HeaderId">
                                <p>@result.ShortDescription</p>
                                <p>@result.LongDescription</p>

                                <br />
                                <h5 class="text-success">Enhancements</h5>
                                <hr class="hr hr-blurry" />
                                <ul class="">
                                    @foreach (var detail in result.Detail)
                                    {
                                        if (detail.Type == 1)
                                        {
                                            <li class="">
                                                @detail.Name
                                                <div class="detail-description innerHTMLDesc">
                                                    @* &#8226; *@
                                                    @detail.Description
                                                </div>
                                            </li>
                                        }
                                    }
                                </ul>

                                <br />
                                <h5 class="text-danger">Bug Fixes</h5>
                                <hr class="hr hr-blurry" />
                                <ul class="">
                                    @foreach (var detail in result.Detail)
                                    {
                                        if (detail.Type == 2)
                                        {
                                            <li class="">
                                                @detail.Name 
                                                <div class="detail-description innerHTMLDesc">
                                                    @* &#8226; *@
                                                    @detail.Description
                                                </div>
                                            </li>
                                        }
                                    }
                                </ul>
                            </div>
                            
                            <button data-pdfPrintReleaseDate="@result.ReleaseDate.ToString("yyyy-MM-dd")"
                                    data-pdfPrintID="@result.HeaderId"
                                    data-pdfPrintReleaseName="@result.ReleaseName"
                                    class="jsPDF-btn btn btn-outline-primary">
                                Download PDF
                            </button>

                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>
@section scripts{
    <script>

        document.querySelectorAll(".jsPDF-btn").forEach(btn => {
            btn.addEventListener("click", (e) => {
                // get btn details
                const element = document.querySelector(`.print-${btn.dataset.pdfprintid}`);

                const div = document.createElement("div")

                //<img src='https://i.ibb.co/KLt38B1/logo.png' style="">
                
                div.innerHTML = `
                            <div class="d-flex justify-content-between align-items-center">
                                <img src='js/image.png' style="" alt="logoImg">

                                <div>
                                    <p class="move-left">Technical_Document</p>
                                    <p class="move-left up">${new Date().toLocaleDateString()}</p>
                                </div>
                            </div>
                            <h3 class="accordion-header mb-1 text-center">
                                        ${btn.dataset.pdfprintreleasename}
                            </h3>
                            <br />
                            <p>Date: ${btn.dataset.pdfprintreleasedate}</p>
                            ${element.innerHTML}
                        `
                //print pdf
                window.jsPDF = window.jspdf.jsPDF;

                const doc = new jsPDF()

                doc.html(div, {
                    callback: function (doc) {
                        // Save the PDF
                        doc.save(`${btn.dataset.pdfprintreleasename.replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g, "")}`);
                    },
                    margin: [10, 10, 10, 10],
                    autoPaging: 'text',
                    x: 0,
                    y: 0,
                    width: 190, //target width in the PDF document
                    windowWidth: 820 //window width in CSS pixels
                });

                // 7/24 - test footer and header

                console.log('test\n')

            })
        })

        window.onload = function(){
            document.querySelectorAll(".innerHTMLDesc").forEach(des => {
                des.innerHTML = des.innerText.toString()

                /*
                let div = des.innerHTML
                div = div.replace(/&gt;/g, ">")
                div = div.replace(/&lt;/g, "<")
                div = div.replace(/&nbsp;/g, " ")
                div = div.replace(/&amp;/g, "&")
                div = div.replace(/&quot;/g, '"');
                div = div.replace(/&apos;/g, "'");
                
                des.innerHTML = div.toString();*/
            })
        }

    </script>
}

<ejs-scripts></ejs-scripts>

taskui/Pages/TableView.cshtml
@page "/Edit"
@model taskui.Pages.TableViewModel
@using Syncfusion.EJ2.RichTextEditor
@{
    ViewData["Title"] = "Edit page";
    int textEditorCount = 1;
}
<div class="white-bg-container">

    <p class="page-title">
        Edit Table
    </p>
    <button id="submitBtn" data-btnType="submitTableView" class="btn btn-primary mb-3">Save Changes</button>

    <ul class="mb-4 ">
        @foreach (var header in Model.HeaderList)
        {
            @if (header.Detail.Count() != 0)
            {
                int detailCount = 1;

                <li class="p-3 mb-5 list-container bg-body-tertiary table-list-container card">
               
                <div class="d-flex justify-content-between">
                    <div>
                        <p class="h4 mt-1">@header.ReleaseName.ToUpper()</p>
                    </div>
                    <p>
                        <a type="button" class="btn btn-secondary" href="/SubmitHeader/AddOneDetail/@header.HeaderId">Add detail</a>
                        @*
                            <button data-bs-target="#@header.HeaderId" class="btn btn-outline-primary" type="button" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseExample">
                                Hide Details
                            </button>
                        *@
                        @if (header.Detail.Count() == 1)
                        {
                            <a class="btn btn-danger ml-1"
                                href="/SubmitHeader/deleteAPage/@header.HeaderId">Delete Release</a>
                        }
                    </p>
                </div>


                <div class="input-group mb-3 mt-2">
                    <span class="input-group-text list-releaseHeaderID">@header.HeaderId</span>
                    <input value="@header.ReleaseName" type="text" class="form-control list-releaseName" placeholder="Release Name" aria-label="Username">
                    <input value="@header.ReleaseDate.ToString("yyyy-MM-dd")" type="date" class="form-control list-releaseDate" placeholder="Release Type" aria-label="Server">
                    <input value="@header.ShortDescription" type="text" class="form-control list-releaseShortDescription" placeholder="Short Description" aria-label="Server">
                </div>
                <div class="form-floating">
                    <input value="@header.LongDescription" type="text" class="form-control list-releaseLongDescription" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Long Description</label>
                </div>

                <div class="mt-3" id="@header.HeaderId">
                    <div class="">
                        @foreach (var headerDetail in header.Detail)
                        {
                            string textEditorId = $"defaultRTE-{textEditorCount++}";

                            <div class="list-detailContainer">

                                <div class="d-flex justify-content-between mb-2">
                                    <div class="mt-3">
                                        <h6 class=" smaller-h6">
                                        </h6>
                                        <p class="h5">@(detailCount++). @headerDetail.Name</p>
                                    </div>
                                    <p>
                                        @if (header.Detail.Count() != 1)
                                        {
                                            <a class="btn btn-danger mt-3"
                                               href="/SubmitHeader/DeleteOneDetail/@headerDetail.DetailId">Delete Detail</a>
                                        }
                                    </p>
                                </div>

                                <div class="input-group mb-3">
                                    <span class="input-group-text list-detail-detailID">@headerDetail.DetailId</span>
                                    <input class="form-control list-detail-detailName" value="@headerDetail.Name" type="text" placeholder="Detail Name" aria-label="Username">
                                    <select class="form-select list-detail-detailType" aria-label="Default select example">
                                        @if (headerDetail.Type == 1)
                                        {
                                            <option selected value="1">Enhancement</option>
                                            <option value="2">Bug Fix</option>
                                        }
                                        else
                                        {
                                            <option value="1">Enhancement</option>
                                            <option selected value="2">Bug Fix</option>
                                        }
                                    </select>
                                </div>

                                <div class="input-group">
                                    <ejs-richtexteditor created="created"
                                    id="@textEditorId" value="@headerDetail.Description">
                                        
                                    </ejs-richtexteditor>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </li>
            }
        }
    </ul>
    
    <script>
        var rteObj

        function created(){
            rteObj = this;
            rteObj.insertImageSettings.saveFormat = 'Base64';
        }
    </script>
    @*
        <br />
        <br />
        <br />
        <table class="table table-hover ">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Release Name</th>
                    <th scope="col">Release Date</th>
                    <th scope="col">Short Description</th>
                    <th scope="col" class="long-description-col">Long Description</th>
                    <th scope="col">DetailId</th>
                    <th scope="col">Type</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var header in Model.HeaderList)
                {
                    bool checkIfFirst = true;
                    foreach (var detail in header.Detail)
                    {
                        string releaseNameClassName = $"trReleaseNameMain{header.HeaderId} form-control form-control-sm";
                        string releaseDateClassName = $"trReleaseDateMain{header.HeaderId} form-control form-control-sm";
                        string shortDescriptionClassName = $"trShortDescriptionMain{header.HeaderId} form-control form-control-sm";
                        string longDescriptionClassName = $"trLongDescriptionMain{header.HeaderId} form-control";
                        <tr class="headerTr">
                            <td class="trHeaderId ">@header.HeaderId</td>
                            <td class="">
                                @if (checkIfFirst)
                                {
                                    <input value="@header.ReleaseName" class="@releaseNameClassName" type="text" placeholder="Name..." />
                                }
                            </td>
                            <td class="">
                                @if (checkIfFirst)
                                {
                                    <input value="@header.ReleaseDate.ToString("yyyy-MM-dd")" class="@releaseDateClassName" type="date" placeholder="Date..." />
                                }
                            </td>
                            <td class="">
                                @if (checkIfFirst)
                                {
                                    <input value="@header.ShortDescription" class="@shortDescriptionClassName" type="text" placeholder="Description..." />
                                }
                            </td>
                            <td class="long-col">
                                @if (checkIfFirst)
                                {
                                    <textarea class="@longDescriptionClassName" placeholder="Long Description here..." id="floatingTextarea">@header.LongDescription</textarea>
                                }
                            </td>
                            <td class="trDetailId">@detail.DetailId</td>
                            <td class="">
                                <select class="trType detailType form-select" aria-label="Default select example">
                                    @if (detail.Type == 1)
                                    {
                                        <option selected value="1">1 - Enhancements</option>
                                        <option value="2">2 - Bugs/Fixes</option>
                                    }
                                    else
                                    {
                                        <option value="1">1 - Enhancements</option>
                                        <option selected value="2">2 - Bugs/Fixes</option>
                                    }
                                </select>
                            </td>
                            <td class="">
                                <input value="@detail.Name" class="trName detailName form-control form-control-sm" type="text" placeholder="Name..." />
                            </td>
                            <td class="">
                                <input value="@detail.Description" class="trDesc detailName form-control form-control-sm" type="text" placeholder="Description..." />
                            </td>
                            <td class="">
                                @if (header.Detail.Count() != 1)
                                {
                                    <a class="btn btn-danger deleteDetailBtnOnTable"
                                        href="/SubmitHeader/DeleteOneDetail/@detail.DetailId">Delete</a>
                                }
                                else
                                {
                                    <a class="btn btn-danger deleteDetailBtnOnTable"
                                        href="/SubmitHeader/deleteAPage/@header.HeaderId">Delete</a>
                                }
                            </td>
                            <td>
                                @if (checkIfFirst)
                                {
                                    <a class="btn btn-secondary deleteDetailBtnOnTable"
                                        href="/SubmitHeader/AddOneDetail/@header.HeaderId">Add</a>
                                }
                            </td>
                        </tr>
                        checkIfFirst = false;
                    }
                }
            </tbody>
        </table>
    *@
</div>

<ejs-scripts></ejs-scripts>